from lib.models.module import *
from lib.models.humormodel1 import *
from lib.models.humormodel2 import *
from lib.models.nammodel import *
from lib.models.humorx2 import *
from lib.models.bertmodel import *
from lib.models.cnnmodel import *
from lib.models.kblstm import *
from lib.models.multicnn import *